//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_sistema_gestion_ventas_electronicosEntities : DbContext
    {
        public db_sistema_gestion_ventas_electronicosEntities()
            : base("name=db_sistema_gestion_ventas_electronicosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<categoria_marca> categoria_marca { get; set; }
        public virtual DbSet<marca> marca { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
