//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int producto_id { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public decimal precio_venta { get; set; }
        public int stock { get; set; }
        public int stock_minimo { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public System.DateTime fecha_ultima_modificacion { get; set; }
        public int estado { get; set; }
        public int marca_id { get; set; }
        public int categoria_id { get; set; }
        public int proveedor_id { get; set; }
    
        public virtual categoria_marca categoria_marca { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
