//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        public int proveedor_id { get; set; }
        public string cuit { get; set; }
        public string nombre_comercial { get; set; }
        public string razon_social { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public System.DateTime fecha_ultima_modificacion { get; set; }
        public int estado { get; set; }
    }
}
